//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTFD.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTFD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 BlueColor 的本地化字符串。
        /// </summary>
        internal static string BlueColor {
            get {
                return ResourceManager.GetString("BlueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BlueColor2 的本地化字符串。
        /// </summary>
        internal static string BlueColor2 {
            get {
                return ResourceManager.GetString("BlueColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChartColor1 的本地化字符串。
        /// </summary>
        internal static string ChartColor1 {
            get {
                return ResourceManager.GetString("ChartColor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChartColor2 的本地化字符串。
        /// </summary>
        internal static string ChartColor2 {
            get {
                return ResourceManager.GetString("ChartColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChartColor3 的本地化字符串。
        /// </summary>
        internal static string ChartColor3 {
            get {
                return ResourceManager.GetString("ChartColor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ConnectionString 的本地化字符串。
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Global\Resource\DefaultInfo.json 的本地化字符串。
        /// </summary>
        internal static string DefaultInfoPath {
            get {
                return ResourceManager.GetString("DefaultInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GrayColor 的本地化字符串。
        /// </summary>
        internal static string GrayColor {
            get {
                return ResourceManager.GetString("GrayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GreenColor 的本地化字符串。
        /// </summary>
        internal static string GreenColor {
            get {
                return ResourceManager.GetString("GreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Global\Resource\Setup.json 的本地化字符串。
        /// </summary>
        internal static string SetupFilePath {
            get {
                return ResourceManager.GetString("SetupFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WathetColor 的本地化字符串。
        /// </summary>
        internal static string WathetColor {
            get {
                return ResourceManager.GetString("WathetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WathetColor2 的本地化字符串。
        /// </summary>
        internal static string WathetColor2 {
            get {
                return ResourceManager.GetString("WathetColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WathetColor3 的本地化字符串。
        /// </summary>
        internal static string WathetColor3 {
            get {
                return ResourceManager.GetString("WathetColor3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Y2 的本地化字符串。
        /// </summary>
        internal static string Y2 {
            get {
                return ResourceManager.GetString("Y2", resourceCulture);
            }
        }
    }
}
